list/urls.py
from . import views
from django.urls import path

# add url paths for views

urlpatterns = [
    path('', views.EntryList.as_view(), name='home'),
    path('add/', views.AddView.as_view(), name='add'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('note/<item_id>/', views.add_note, name='note'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
    path('home/star/<item_id>', views.toggle_star, name='toggle_star'),
    path('home/check/<item_id>', views.toggle_check, name='toggle_check'),
]

shoppinglist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('list.urls'), name='list_urls'),
    path('accounts/', include('allauth.urls')),
]

list/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# category will appear as a drop down list to user to choose from
CATEGORY_CHOICES = [
    ('a', 'Fresh'),
    ('b', 'Dairy'),
    ('c', 'Frozen'),
    ('d', 'Bakery'),
    ('e', 'Dry Ingredients'),
    ('f', 'Household'),
    ('g', 'Pet'),
    ('h', 'Personal Care'),
    ('i', 'Treats'),
    ('j', 'Alcohol')
]

# user can choose from a number in the drop down list
QUANTITY_CHOICES = [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5')
]


class Entry(models.Model):

    # set attributes for List items Table
    item_name = models.CharField(
        max_length=60, null=False, blank=False)
    quantity = models.IntegerField(
        choices=QUANTITY_CHOICES, default='1')
    star = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(
        max_length=20, choices=CATEGORY_CHOICES, default='Fresh')
    added_on = models.DateTimeField(auto_now_add=True)
    check_item_as_done = models.BooleanField(default=False)

    # helper methods
    class Meta:
        ordering = ['-added_on', '-star', ]

    def __str__(self):
        return self.item_name


class Note(models.Model):

    # set attributes for Notes Table
    item = models.OneToOneField(
        Entry, on_delete=models.CASCADE, related_name='notes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    added_on = models.DateTimeField(auto_now_add=True)

    # helper method
    def __str__(self):
        return self.body

list/forms.py
from .models import Entry, Note
from django import forms


class AddForm(forms.ModelForm):
    """Form to add a new Item to the user's shopping list"""
    class Meta:
        model = Entry
        fields = ('item_name', 'quantity', 'star', 'category',)


class NoteForm(forms.ModelForm):
    """Form to add a Note to an item on the user's shopping list"""
    class Meta:
        model = Note
        fields = ('body',)

list/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.views.generic.edit import (
    FormView, CreateView, UpdateView, DeleteView)
from django.http import HttpResponseRedirect
from .models import Entry, Note
from .forms import AddForm, NoteForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required


CATEGORY_CHOICES = [
    ('a', 'Fresh'),
    ('b', 'Dairy'),
    ('c', 'Frozen'),
    ('d', 'Bakery'),
    ('e', 'Dry Ingredients'),
    ('f', 'Household'),
    ('g', 'Pet'),
    ('h', 'Personal Care'),
    ('i', 'Treats'),
    ('j', 'Alcohol')
]


@login_required(login_url='/account/login.html')
def get_context_data(self, **kwargs):
    profile = Profile.objects.get(user=self.kwargs['pk'])
    context = {
        'profile': profile,
        'form': ProfileForm(instance=profile)
    }
    return context


class EntryList(LoginRequiredMixin, generic.ListView):
    """A logged in User will be able to view their entire
    shopping list in the Home page, and have access to all the features
    of the list ie. CRUD, Search and Adding Notes"""

    model = Entry
    template_name = 'index.html'
    paginate_by = 100

    def test_func(self):
        return self.request.user == self.get_object().user

    def get_queryset(self, **kwargs):
        queryset = Entry.objects.filter(user=self.request.user)
        search = self.request.GET.get('query')
        
        if search:
            queryset = queryset.filter(
                Q(category__icontains=search) |
                Q(item_name__icontains=search) |
                Q(category__in=[
                    choice[0] for choice in CATEGORY_CHOICES if
                    choice[1].lower().startswith(search.lower())])

            )
        return queryset


class AddView(FormView):
    """Create a new shopping list entry using the fields from Entry model"""

    template_name = 'add_to_list.html'
    form_class = AddForm
    success_url = reverse_lazy('home')

    # ensure new items are automatically saved to the logged in user
    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = User.objects.get(id=self.request.user.id)
        messages.success(self.request, 'Added successfully.')
        form.save()
        return super().form_valid(form)


class EditView(UserPassesTestMixin, UpdateView):
    """Edit shopping list entry using the entry's primary key"""

    model = Entry
    template_name = 'edit_entry.html'
    form_class = AddForm
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('home')

    # extra security - only permit edit if logged-in user created item
    def test_func(self):
        return self.request.user == self.get_object().user

    def form_valid(self, form):
        messages.success(self.request, 'Edited successfully.')
        instance = form.save()
        return super(EditView, self).form_valid(form)


def add_note(request, item_id):
    # get an instance of the shopping list item with an id equal to the
    # one that was clicked in the index.html template but
    # call the note.html template having populated it with the shopping
    # list item name and add our note to the body field, return to 'Home'

    entry = get_object_or_404(Entry, id=item_id)
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            try:
                entry = Entry.objects.get(id=item_id)
            except Entry.DoesNotExist:
                pass
            instance.item = entry
            instance.user = request.user
            instance.save()
            return redirect('home')
    else:
        form = NoteForm()
    context = {
        'entry': entry,
        'form': form
    }
    return render(request, 'note.html', context)


class Delete(UserPassesTestMixin, DeleteView):
    """Target the entry with the pk again to Delete Item"""

    model = Entry
    pk_url_kwarg = 'pk'
    template_name = 'delete.html'
    success_url = reverse_lazy('home')
    success_message = "Deleted successfully."

    # extra security - only permit delete if logged-in user created item
    def test_func(self):
        return self.request.user == self.get_object().user

    def form_valid(self, form):
        instance = form.save()
        return super(Delete, self).form_valid(form)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(Delete, self).delete(request, *args, **kwargs)


def toggle_star(request, item_id):
    # toggle the star state to On/Off

    item = get_object_or_404(Entry, id=item_id)
    item.star = not item.star
    item.save()
    return redirect('home')


def toggle_check(request, item_id):
    # toggle the checkbox state to On/Off

    item = get_object_or_404(Entry, id=item_id)
    item.check_item_as_done = not item.check_item_as_done
    item.save()
    return redirect('home')

templates/add_to_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- template for AddView to add a new item to the user's 
shopping list -->

{% block content %}

<div class="row justify-content-center">
    <h2 class="mt-3">Add to The Shopping List:</h2>
</div>
<div class="container pt-3">
    <!-- from bootstrap -->
    <form method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group row offset-md-2">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
            <div class="col-sm-8">
                {{ field|add_class:'form-control col-sm-8'}}
            </div>
            {% for error in field.errors %}
            <span class="help-block">{{error}}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group pt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{% url 'home' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="The Shopping List application for personal organisation">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- link to bootstrap -->

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- link to css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <!-- font awesome kit code -->
  <script src="https://kit.fontawesome.com/785586cce1.js" crossorigin="anonymous"></script>

  <!-- Application title -->
  <title>THE SHOPPING LIST</title>
</head>

<!-- Content -->

<body class="dark-bg">

  <!-- navigation -->
  <header>

    <!-- Checks whether the current url name is being used and if it is
        turn on the active class to underline that navigation link name -->
    {% with request.resolver_match.url_name as url_name %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="nav bg-dark">
          <a class="navbar-brand" href="{% url 'home' %}"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">


              <!-- Checks that a registered user is logged in 
                        and changes navigation bar content to Home, 
                        Logout and Search bar-->

              {% if user.is_authenticated %}
              <a class="nav-item nav-link {% if url_name == 'home' %}active{% endif %} text-white"
                href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link {% if url_name == 'account_logout' %}active{% endif %} text-white"
                href="{% url 'account_logout' %}">Logout</a>

            </div>
          </div>
        </div>
        <form class="d-inline-flex" role="search" method="GET" action="{% url 'home' %}">
          <input class="form-control me-2" name="query" type="search" placeholder="Search Item or Category"
            aria-label="Search Item or Category" style="align-self: center;">
          <button class="btn btn-outline-success ml-1" type="submit">Search</button>
        </form>

        <!-- Else navigation bar contains only Register 
        and Login to prevent unauthorised users proceeding -->
        {% else %}
        <a class="nav-item nav-link {% if url_name == 'account_signup' %}active{% endif %} text-white"
          href="{% url 'account_signup' %}">Register</a>
        <a class="nav-item nav-link {% if url_name == 'account_login' %}active{% endif %} text-white"
          href="{% url 'account_login' %}">Login</a>

        {% endif %}

      </div>
      </div>
      </div>

      </div>
    </nav>
    {% endwith %}

    <!-- heading -->
    <div class="heading-sm text-center">
      <h1 class="m-5">
        THE SHOPPING LIST<br>Organised | Everywhere
      </h1>
    </div>
  </header>

  <!-- Django flash messages -->

  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="close btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endfor %}
      </div>
    </div>
  </div>

  <!-- main shopping list container -->
  <div class="container bg-light">
    {% block content %}
    <!-- content goes here -->
    {% endblock %}

  </div>



  <!-- footer -->

  <footer class="footer mt-auto py-4 light-bg bg-dark">

    <p class="m-0 text-center text-white">
      Made by Monica Murray for CI P4
      <a href="https://github.com/MoniMurray/shopping-list" target="_blank" rel="noopener"
        aria-label="Visit my Github profile to see more about this project (Opens a new browser page)">
        <i class="fa-brands fa-github pl-1"></i></a></p>
    <p class="m-0 text-center text-white">Follow me: <a href="https://www.facebook.com" target="_blank" rel="noopener"
        aria-label="Visit my Facebook page (Opens a new browser page)"><i class="fa-brands fa-facebook pl-2"></i></a>
      <a href="https://www.instagram.com" target="_blank" rel="noopener"
        aria-label="Visit my Instagram page (Opens a new browser page)"><i class="fa-brands fa-instagram pl-2"></i></a>
      <a href="https://www.twitter.com" target="_blank" rel="noopener"
        aria-label="Visit my Twitter page (Opens a new browser page)"><i class="fa-brands fa-twitter pl-2"></i></a>


  </footer>

  <!-- Use Javascript to automatically dismiss flash success 
        messages after a 3 second delay -->

  <script>
    setTimeout(function () {
      let messages = document.getElementById("msg");
      let alert = new bootstrap.Alert(messages);
      alert.close();
    }, 3000);
  </script>

  <!-- link to js -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

</body>

</html>

templates/delete.html
{% extends 'base.html' %}

<!-- template for Delete a shopping list item -->

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <h3 class="mt-3">Deleting {{ entry.item_name }} from your Shopping List:</h3>
    </div>
    <div class="container pt-5">
        <form method="post">
            {% csrf_token %}
            <p class="text-capitalize">Are you sure you want to delete {{ entry.item_name }}?</p>
            {% for error in field.errors %}
            <span class="help-block">{{error}}</span>
            {% endfor %}

            <div class="form-group pt-3">
                <button type="submit" class="btn btn-primary mb-3">Delete</button>
                <a href="{% url 'home' %}" class="btn btn-default mb-3">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_entry.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- template for EditView to call an item by its id and render the 
pre-populated form to the user for 'editing' -->

{% block content %}

<div class="row justify-content-center">
    <h2 class="text-capitalize mt-3">Edit {{entry}}:</h2>
</div>

<div class="container pt-3">
    <!-- from bootstrap -->
    <form method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group row offset-md-2">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
            <div class="col-sm-8">
                {{ field|add_class:'form-control col-sm-8 text-capitalize'}}
            </div>
            {% for error in field.errors %}
            <span class="help-block">{{error}}</span>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group pt-3">
            <button type="submit" class="btn btn-primary mb-3">Submit</button>
            <a href="{% url 'home' %}" class="btn btn-default mb-3">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Shopping List Image -->
<div class="image-container mt-3">
  <img src="https://res.cloudinary.com/dyiiqx4el/image/upload/v1681314926/shopping_bags_fxp2hm.webp" class="img-fluid"
    width="auto" height="auto" alt="" />

</div>

<div class="card-body justify-content-center">
  
    <!-- If a user is authorised, display their Shopping List
    items in a table with each item row containing additional features -->

    {% if user.is_authenticated %}

    <div class="table-responsive-sm table-bordered pt-1">
      <h1>{{user.username}}'s List</h1>

      <!-- Link to Add a shopping list item -->
      <button type="button" class="btn btn-lg mb-1">
        <a href="{% url 'add' %}">Add Item</a>
      </button>

      <!-- Table  -->
      <div style="max-width: 100%; max-height: 400px; overflow-y: scroll">
        <table class="table">

          <!-- Table heading row -->
          <thead>
            <tr>
              <th scope="col" class="w-auto"></th>
              <th scope="col" class="w-50">Items</th>

              <th scope="col" class="w-auto">Quantity</th>
              <th scope="col" class="w-auto">Done</th>
              <th scope="col" class="w-auto">Edit</th>
              <th scope="col" class="w-auto">Delete</th>
            </tr>
          </thead>

          <!-- Table body containing a shopping list item and it's 
            features in its own table row -->
          <tbody>
            {% for entry in entry_list %}

            <tr>

              <!-- Toggle Star on/off to mark item Urgent -->
              {% if entry.star %}
              <td>
                <a href="{% url 'toggle_star' entry.id %}">
                  <i class="fa-solid fa-star" aria-label="font awesome solid star icon" style="color: gold"></i>
                </a>
              </td>

              {% else %}
              <td>
                <a href="{% url 'toggle_star' entry.id %}">
                  <i class="fa-regular fa-star" aria-label="font awesome regular star icon" style="color: gold"></i>
                </a>
              </td>

              {% endif %}

              <!-- Toggle on/off Mark item as Done  -->
              {% if entry.check_item_as_done %}

              <td class="text-capitalize">
                <strike> {{ entry.item_name }} </strike>
              </td>
              <td>{{entry.quantity}}</td>
              <td>
                <a href="{% url 'toggle_check' entry.id %}">

                  <i class="fa-solid fa-square-check" aria-label="font awesome solid checkbox icon"></i>

                </a>
              </td>
              <td></td>
              <td>
                <a href="{% url 'delete' entry.id %}"><i class="fa-solid fa-trash-can"
                    aria-label="font awesome trash-can delete icon"></i>
                  Delete</a>
              </td>

              {% else %}
              <!-- add a Note to a Shopping list item -->
              <td class="text-capitalize">
                {{ entry.item_name }}
                  {% if entry.notes %}
                  <p class="text-capitalize font-italic text-wrap">

                    <i class="fa-regular fa-message text-center" aria-label="font awesome regular add note icon"></i>
                    {{entry.notes}}
                  </p>
                  {% else %}
                  <p>
                    <a href="{% url 'note' entry.id %}">
                      <i class="fa-regular fa-message text-center" aria-label="font awesome regular add note icon"></i>
                    </a>
                    {{entry.notes}}
                  </p>
                {% endif %}
              </td>
              <td>{{entry.quantity}}</td>
              <td>
                <a href="{% url 'toggle_check' entry.id %}">
                  <i class="fa-regular fa-square" aria-label="font awesome regular checkbox icon"></i>
                </a>
              </td>

              <!-- Edit the Shopping list item, target by it's id -->
              <td>
                <a href="{% url 'edit' entry.id %}">
                  <i class="fa-solid fa-pencil" aria-label="font awesome solid pencil icon"></i> Edit</a>
              </td>

              <!-- Delete the Shopping list item, target by it's id -->
              <td>
                <a href="{% url 'delete' entry.id %}">
                  <i class="fa-solid fa-trash-can" aria-label="font awesome solid trash-can delete icon"></i> Delete</a>
              </td>

              {% endif %}
            </tr>

            <!-- if there are no items in the shopping list -->
            {% empty %}
            <tr>
              No items to display.
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>

    {% else %}


  
</div>
{% endif %}
</div>
{% endblock %}

templates/note.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- Template for add_note to enable the User to add an additional
note to an item on their shopping list -->

{% block content %}

<div class="container pt-3 ">
    <!-- from bootstrap -->
    <h2>Add a Note:</h2>
    <p>Note added by {{user.username}}</p>
    <form method="post" style="margin-top: 1.3em;">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group row offset-md-2">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{ field.label }}:</label>
            <div class="col-sm-8">
                {{ field|add_class:'form-control col-sm-8 text-capitalize'}}
            </div>
            {% for error in field.errors %}
            <span class="help-block">{{error}}</span>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group pt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{% url 'home' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}